apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-fastapi
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "wiki-chart.fullname" . }}-fastapi
  ports:
    - port: {{ .Values.fastapi.servicePort }}
      targetPort: {{ .Values.fastapi.servicePort }}
