apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
